{
 "title": "Autoscaler Metrics",
 "description": "To help you getting started with your swarm autoscaler metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU 30Sec (Upscale)",
   "type": "timeseries",
   "description": "Shows cpu usage of services based on 30 second average. \nYou can change the prometheus query at [30s], if you want to edit autoscale.cpu_upscale_time_duration. \nUse this link to see what to enter instead of [30s] (Must be a multiplier of [30s]): https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~'.+'}[30s])) BY (container_label_com_docker_swarm_service_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 5Min (Downscale)",
   "type": "timeseries",
   "description": "Shows cpu usage of services based on 5 minute average. \nYou can change the prometheus query at [5m], if you want to edit autoscale.cpu_downscale_time_duration. \nUse this link to see what to enter instead of [5m] (Must be a multiplier of [30s]): https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~'.+'}[5m])) BY (container_label_com_docker_swarm_service_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory 30Sec (Upscale)",
   "type": "timeseries",
   "description": "Shows memory usage of services based on 30 seconds average. You can change the prometheus query at [30s], if you want to edit autoscale.memory_upscale_time_duration. \nUse this link to see what to enter instead of [30s] (Must be a multiplier of [30s]): https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{container_label_com_docker_swarm_task_name=~'.+'}[30s])) BY (container_label_com_docker_swarm_service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory 5Min (Downscale)",
   "type": "timeseries",
   "description": "Shows memory usage of services based on 5 minute average. You can change the prometheus query at [5m], if you want to edit autoscale.memory_downscale_time_duration. \nUse this link to see what to enter instead of [5m] (Must be a multiplier of [30s]): https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{container_label_com_docker_swarm_task_name=~'.+'}[5m])) BY (container_label_com_docker_swarm_service_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}